
package tips;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TipService", targetNamespace = "http://tips/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface TipServiceInterface {

    /**
     * 
     * @return
     *         returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTips", targetNamespace = "http://tips/", className = "tips.GetTips")
    @ResponseWrapper(localName = "getTipsResponse", targetNamespace = "http://tips/", className = "tips.GetTipsResponse")
    @Action(input = "http://tips/TipService/getTipsRequest", output = "http://tips/TipService/getTipsResponse")
    public List<String> getTips();

    /**
     * 
     * @return
     *         returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTip", targetNamespace = "http://tips/", className = "tips.GetTip")
    @ResponseWrapper(localName = "getTipResponse", targetNamespace = "http://tips/", className = "tips.GetTipResponse")
    @Action(input = "http://tips/TipService/getTipRequest", output = "http://tips/TipService/getTipResponse")
    public String getTip();

}
